language: python
dist: trusty
python:
  - 3.4
  - 3.5
notifications:
  email: false
addons:
  apt:
    packages:
        - libblas-dev
        - liblapack-dev
env:
    global:
        # Maximal dependencies
        - DEPENDS="cython numpy scipy matplotlib"
before_install:
  - source travis-tools/utils.sh
  - travis_before_install
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository -y ppa:marutter/c2d4u
  - sudo add-apt-repository -y ppa:marutter/rrutter
  - sudo apt-get update
  - sudo apt-get install -y r-base r-base-dev r-cran-devtools r-cran-rcpp


install:
  # Install selection
  - git submodule update --init 
  - cd R-selective
  - git submodule update --init 
  - sudo make install
  - Rscript -e "install.packages(c('glmnet', 'intervals', 'adaptMCMC', 'gglasso'), repos='http://cloud.r-project.org')"
  - cd ../regreg
  - pip install -r requirements.txt
  - pip install -e .
  - cd ../selective-inference
  - git submodule update --init 
  - pip install  -r requirements.txt; 
  - pip install -e .
  - cd ..

# command to run tests, e.g. python setup.py test
script:
    - python compare.py --instance AR_instance --nsample 100 --nfeature 50 --nsignal 10 --methods lee_theory liu_theory --htmlfile AR.html --signal 3 4 5 --rho 0 0.5 --csvfile AR.csv
